# Generated by Django 5.1.1 on 2024-09-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logId', models.BigIntegerField(unique=True)),
                ('activityName', models.CharField(max_length=100)),
                ('activityTypeId', models.IntegerField()),
                ('averageHeartRate', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('duration', models.BigIntegerField()),
                ('activeDuration', models.BigIntegerField()),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('logType', models.CharField(max_length=50)),
                ('lastModified', models.DateTimeField()),
                ('startTime', models.DateTimeField()),
                ('originalStartTime', models.DateTimeField()),
                ('originalDuration', models.BigIntegerField()),
                ('elevationGain', models.FloatField(blank=True, null=True)),
                ('hasGps', models.BooleanField(default=False)),
                ('shouldFetchDetails', models.BooleanField(default=False)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('distanceUnit', models.CharField(blank=True, max_length=10, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('pace', models.FloatField(blank=True, null=True)),
                ('swimLengths', models.IntegerField(blank=True, null=True)),
                ('poolLength', models.FloatField(blank=True, null=True)),
                ('poolLengthUnit', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=10, unique=True)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('ab_person', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('max_heart_rate', models.IntegerField()),
                ('run_5km_date', models.DateField()),
                ('run_5km_minutes', models.IntegerField()),
                ('run_5km_seconds', models.IntegerField()),
                ('stride_walk', models.FloatField()),
                ('stride_run', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logId', models.BigIntegerField(unique=True)),
                ('dateOfSleep', models.DateField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('duration', models.BigIntegerField()),
                ('minutesToFallAsleep', models.IntegerField()),
                ('minutesAsleep', models.IntegerField()),
                ('minutesAwake', models.IntegerField()),
                ('minutesAfterWakeup', models.IntegerField()),
                ('timeInBed', models.IntegerField()),
                ('efficiency', models.IntegerField()),
                ('sleep_type', models.CharField(choices=[('stages', 'Stages'), ('classic', 'Classic')], max_length=10)),
                ('infoCode', models.IntegerField()),
                ('mainSleep', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('tracker_id', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('tracker_features', models.JSONField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='quality_checks.fitbitexercise')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('minutes', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_levels', to='quality_checks.fitbitexercise')),
            ],
        ),
        migrations.CreateModel(
            name='HeartRateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('minutes', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_zones', to='quality_checks.fitbitexercise')),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_time_frame', models.DateTimeField()),
                ('injuries', models.JSONField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitVeryActiveMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitTimeInHeartRateZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('below_default_zone_1', models.FloatField()),
                ('in_default_zone_1', models.FloatField()),
                ('in_default_zone_2', models.FloatField()),
                ('in_default_zone_3', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitSleepScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sleep_log_entry_id', models.BigIntegerField()),
                ('overall_score', models.IntegerField()),
                ('composition_score', models.IntegerField()),
                ('revitalization_score', models.IntegerField()),
                ('duration_score', models.IntegerField()),
                ('deep_sleep_in_minutes', models.IntegerField()),
                ('resting_heart_rate', models.FloatField()),
                ('restlessness', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitSedentaryMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitRestingHeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value_date', models.DateField()),
                ('value', models.FloatField()),
                ('error', models.FloatField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitModeratelyActiveMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitLightlyActiveMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitHeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('bpm', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.AddField(
            model_name='fitbitexercise',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview'),
        ),
        migrations.CreateModel(
            name='FitbitDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('value', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('meals', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('glasses_of_fluid', models.IntegerField()),
                ('alcohol_consumed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='SleepLevelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deep_count', models.IntegerField()),
                ('deep_minutes', models.IntegerField()),
                ('deep_thirty_day_avg_minutes', models.IntegerField()),
                ('wake_count', models.IntegerField()),
                ('wake_minutes', models.IntegerField()),
                ('wake_thirty_day_avg_minutes', models.IntegerField()),
                ('light_count', models.IntegerField()),
                ('light_minutes', models.IntegerField()),
                ('light_thirty_day_avg_minutes', models.IntegerField()),
                ('rem_count', models.IntegerField()),
                ('rem_minutes', models.IntegerField()),
                ('rem_thirty_day_avg_minutes', models.IntegerField()),
                ('sleep_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='quality_checks.sleeplog')),
            ],
        ),
        migrations.CreateModel(
            name='SleepLevelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('level', models.CharField(max_length=10)),
                ('seconds', models.IntegerField()),
                ('sleep_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels_data', to='quality_checks.sleeplog')),
            ],
        ),
        migrations.CreateModel(
            name='SleepShortData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('level', models.CharField(max_length=10)),
                ('seconds', models.IntegerField()),
                ('sleep_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_data', to='quality_checks.sleeplog')),
            ],
        ),
        migrations.CreateModel(
            name='SRPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date_time', models.DateTimeField()),
                ('activity_names', models.JSONField()),
                ('perceived_exertion', models.IntegerField()),
                ('duration_min', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
        migrations.CreateModel(
            name='Wellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_time_frame', models.DateTimeField()),
                ('fatigue', models.IntegerField()),
                ('mood', models.IntegerField()),
                ('readiness', models.IntegerField()),
                ('sleep_duration_h', models.FloatField()),
                ('sleep_quality', models.IntegerField()),
                ('soreness', models.IntegerField()),
                ('soreness_area', models.JSONField()),
                ('stress', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview')),
            ],
        ),
    ]
