# Generated by Django 5.1.1 on 2024-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantoverview',
            name='run_5km_date',
            field=models.CharField(max_length=20),
        ),
    ]
