# Generated by Django 5.1.1 on 2024-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0002_alter_participantoverview_run_5km_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantoverview',
            name='stride_run',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='stride_walk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
