# Generated by Django 5.1.1 on 2024-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0003_alter_participantoverview_stride_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantoverview',
            name='max_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
