# Generated by Django 5.1.1 on 2024-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0004_alter_participantoverview_max_heart_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantoverview',
            name='max_heart_rate',
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='ab_person',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='run_5km_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='run_5km_minutes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='run_5km_seconds',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='stride_run',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participantoverview',
            name='stride_walk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
