# Generated by Django 5.1.1 on 2024-09-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0006_participantoverview_max_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitsteps',
            name='dateTime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
