# Generated by Django 5.1.1 on 2024-09-17 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0007_alter_fitbitsteps_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeplog',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quality_checks.participantoverview'),
            preserve_default=False,
        ),
    ]
