# Generated by Django 5.1.1 on 2024-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0009_alter_sleeplog_logid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
