# Generated by Django 5.1.1 on 2024-10-01 21:56

import quality_checks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0010_alter_reporting_date_alter_reporting_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitexercise',
            name='manualValuesSpecified',
            field=models.JSONField(default=quality_checks.models.default_manual_values),
        ),
        migrations.AddField(
            model_name='fitbitexercise',
            name='tcxLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbitexercise',
            name='vo2Max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
