# Generated by Django 5.1.1 on 2024-10-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_checks', '0012_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('expected_records', models.IntegerField()),
                ('expected_variables', models.JSONField()),
                ('constraints', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
